[hotfix] Upgrade urllib3 dependency and downgrade docutils.
The build was failing due to:

RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, 
< 1.22!

in the requests library used by the bbp_client, this upgrade should
resolve the build issue.

It was also failing due to the most recent docutils version being
0.14rc1, whichm is not properly parsed by the sphinx version we
installed. Explicitly add the working docutils version.

Change-Id: I8848dc16b6e6a141069aaec794f225a775aae901